### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

In [10]:
import numpy as np
distances = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

grid = np.array([abs(i-j) for i in distances for j in distances]).reshape(len(distances), len(distances))
print(grid)

km_grid = grid * 1.60934
print(km_grid)

[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
[[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1300.34672 1894.19318 2755.19008]
 [1401.735

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [23]:
N=99
shape_array = np.array([i for i in range(N+1)]).T
mask = np.ones((N+1,), dtype=bool)

import time
start = time.time()
for i in range(2,N+1):
    for j in range(i,N+1):
        if i*j < N+1:
            mask[i*j] = False

print(shape_array[mask])
end = time.time() - start
print(end)

[ 0  1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79
 83 89 97]
0.0008251667022705078


In [24]:
def prime_finder(N:int):
    shape_array = np.array([i for i in range(N+1)]).T
    mask = np.ones((N+1,), dtype=bool)
    start = time.time()
    
    for i in range(2,N+1):
        for j in range(i,N+1):
            if i*j < N+1:
                mask[i*j] = False

    print(shape_array[mask])
    end = time.time() - start
    
    return end

N_array = np.arange(1e2, 1e5, 1e2, dtype=int)

import matplotlib.pyplot as plt

plt.plot(prime_finder(N_array))

TypeError: only integer scalar arrays can be converted to a scalar index

**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

In [18]:
import numpy.random as npr
import numpy as np
npr.seed(1234567)

N_walkers = 1000
N_steps = 200
rand_walk = npr.randint(2,size=(N_walkers,N_steps))
mask = (rand_walk==0)

rand_walk[mask] = -1

print(rand_walk)

walk_distances = np.array([np.sum(rand_walk[i,:]) for i in range(N_walkers)])
#print(walk_distances)

squared_distances = walk_distances ** 2
print(squared_distances)

mean_distances = np.array([np.sum(rand_walk[i,:]) for i in range(N_walkers)]).reshape(N_walkers,)

[[ 1  1 -1 ...  1 -1  1]
 [-1 -1  1 ...  1  1 -1]
 [-1  1  1 ... -1 -1 -1]
 ...
 [-1  1  1 ... -1  1  1]
 [ 1  1 -1 ... -1  1  1]
 [-1  1 -1 ...  1  1 -1]]
[ 144  100  676   36   64  400    0  324   16  784  900   36  784  784
   16  100  576   36  196  324   64   16  400   64   64  100  144  324
    0   36  676    4   16  144  784  256  324 1024   64  196  256  324
  324 1156  100    0   64  676 1156   36  144    4  400  100  144   16
  100  144   16  100  100   16   64    4  100    4    0    0  900   64
    4 1024  144   64  256   16   36  144   16   16  784   16    0    0
   16    4  324  144  100    4  100  484    4  256   16  324   16  324
  324   36  400 1600  144   64 1296  196  484   36    4  144  144   36
  100  144   16   64  100   64  324  256   16 1296   36   16   16   36
    0  400   16   16  676   16  324  100  100   16    0   36  400  400
   36   16  484    4  484    4    4  324   16  100  484   36    0   16
  144    4  900  256   36  144  324   16   64  100  900  144  5

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.