# OSEMN Exercises

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import csv
import json

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [18]:
num = np.random.random(50) #con random accetta un solo argomento che è il numero di elementi 
print(num)
data = np.savetxt("simple_data.txt", num)

[0.89176509 0.66410791 0.43493383 0.5615054  0.41134902 0.34763754
 0.36733023 0.37545404 0.43253632 0.11742516 0.41664228 0.94729114
 0.86628142 0.75672423 0.37404617 0.30278334 0.88480541 0.50186504
 0.92919155 0.02733495 0.86303654 0.63950248 0.95755717 0.64550867
 0.17232427 0.49429511 0.34393134 0.43215531 0.60170726 0.44531365
 0.61145572 0.63469578 0.82273065 0.04951588 0.27189045 0.34912523
 0.05835244 0.17157571 0.39114626 0.88377062 0.90005928 0.83163955
 0.98623989 0.93748374 0.03040637 0.62749452 0.25083505 0.48775781
 0.21898807 0.90491793]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [29]:
matrix = np.random.rand(5,5) #con rand posso mettere la dimensione della matrice come argomento
print(matrix)
matrix = np.savetxt("data.txt", matrix)

[[0.76939426 0.05640964 0.24628612 0.75707713 0.72239074]
 [0.12058299 0.19795794 0.45011822 0.34322617 0.42483252]
 [0.10960912 0.45530955 0.73560982 0.03131404 0.04864228]
 [0.04821642 0.27732275 0.7905604  0.72570656 0.2330473 ]
 [0.99601868 0.10660576 0.85759692 0.93056285 0.41520641]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [30]:
matrix = np.loadtxt("data.txt")
data = matrix.tolist() #converto da array a lista

with open("data.csv", "w") as csvfile: #apro un file csv da modificare
    writer = csv.writer(csvfile) #creo un writer object
    writer.writerows(data) #scrivo sul csv il contenuto delle righe di data

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [6]:
card_list = []
with open("credit_card.dat", "r") as file:
    for line in file:
        line = line.strip()[:-4]
        card_number = ""
        for i in range(0, len(line), 6):
            extract = line[i:i+6]
            card_number += chr(int(extract, 2))
        card_list.append(card_number)
print(card_list)

['7648 5673 3775 2271', '3257 8247 3354 2266', '2722 0001 4011 6652', '0661 3063 3742 3150', '0432 1608 1462 4742', '5827 2027 8785 7303', '5774 8528 2087 1117', '8140 1210 6352 2845', '5764 1133 7301 7100', '6456 1737 4126 6726', '1228 8631 7382 0000', '7051 0160 5374 3166', '0618 3587 1630 6376', '1545 5454 7444 5636', '6735 3116 3202 6834', '7287 5011 1547 8413', '7033 2607 3328 4200', '2568 5244 1874 5024', '1684 2253 7570 7118', '0672 2576 0575 6631', '6332 8353 8787 1340', '1813 3361 1175 4211', '2477 6450 8840 2368', '5512 3505 2563 1326', '3083 7882 0621 0025', '4521 5148 8045 0334', '7563 3654 8713 5787', '8324 2664 0476 5561', '0565 2504 7168 3510', '5107 5507 1767 0738', '2462 1821 2448 1443', '2788 0638 6861 6554', '5851 5873 5474 0547', '0670 1004 4013 2655', '5874 5506 3048 0806', '2805 5401 8462 1260', '5083 8406 6310 1862', '1076 1445 3013 2266', '8440 4804 4844 5277', '4758 6141 0686 1387', '7586 0675 0315 2568', '2544 1258 7432 5165', '3474 5023 4434 5626', '1410 0270

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

In [ ]:
def filter_and_save_users('user_data.json', csv):
    with open('user_data.json', 'r') as file: #carico il file json
        data = json.load(file)
    filtered_data = [user for user in data if user['CreditCardType'] == 'American Express']
    #filtro per tutti gli user "CreditCardType" == "American Express"
    if filtered_data: #faccio l'if per cominciare a salvare i dati nuovi nel csv
        keys = filtered_data[0].keys()  #prendo il nome del campo dal primo 
        with open(csv, 'w', newline='') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=keys)
            writer.writeheader()
            writer.writerows(filtered_data)
            
filter_and_save_users('path_to_json/user_data.json', 'path_to_csv/filtered_data.csv')

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.