In [1]:
import numpy as np

In [2]:
# ARRAYS 
# Multi-dimensional arrays are possible, and operations with them are quiet efficients.
L = range(1000)
a = np.arange(1000)
%timeit [i**2 for i in L]
%timeit a**2

73.8 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.24 µs ± 4.09 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
# A numpy array is a grid of values with the same type
a = np.array([1,2,3], 'float64') #tutti saranno quindi dei float
b = np.array([1,2,3], 'uint32') #tutti saranno int
print(a, a.dtype)
print(b, b.dtype)
# Anche numeri complessi sono permessi
# Pure booleans
c = np.array([True,False,True,False])
print(c, c.dtype)
# Pure stringhe
d = np.array(['Che', 'Bello', 'Python'])
print(d, d.dtype)

[1. 2. 3.] float64
[1 2 3] uint32
[ True False  True False] bool
['Che' 'Bello' 'Python'] <U6


In [16]:
# DIMENSIONS
a = np.array([1, 2, 3]) #1D
print('rank', a.ndim) #1 dimensione
print('shape', a.shape) #3 elementi nell'array
b = np.array([[1, 2, 3], [4, 5, 6]]) #2D
print('rank', b.ndim) #2 dimensioni (riga e colonna)
print('shape', b.shape) #2 righe e 3 colonne
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
             [[9, 8, 7], [6, 5, 4], [3, 2, 1]]]) #3D (2 righe 3 colonne)
print('rank', c.ndim) #3D
print('shape', c.shape) #2 matrici 3x3

rank 1
shape (3,)
rank 2
shape (2, 3)
rank 3
shape (2, 3, 3)


In [24]:
# INITIALIZING ARRAYS
# A list can be inside an array
l = [1,2,3]
a = np.array(l)
print(a.tolist(), type(a.tolist()))
# To inizialize i remember how it works: 
print(np.arange(1,9,2)) #start, and, steps
print(np.linspace(0,1,20)) #start, end, num-points (for plotting graphs)
# Inizializziamo i più comuni arrays
ones = np.ones((3,3)) #fa una matrice 3 righe 3 colonne di uni
print(ones, '\n')
zeros = np.zeros((2,2)) #fa una matrice 2x2 di zeri
print(zeros, '\n')
unity = np.eye(3) #matrice identità, uguale a np.identity
print(unity, '\n')
diagonal = np.diag(np.array([2,5,3,4])) #matrice con come diagonale l'array inserito
print(diagonal, '\n')
array = np.array([x*x for x in range(3)])
print(array, '\n')
func = np.fromfunction(lambda i,j: (i-2)**2 + (j-i)**2, (5,5))
print(func, '\n')

[1, 2, 3] <class 'list'>
[1 3 5 7]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0.]
 [0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[2 0 0 0]
 [0 5 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[0 1 4] 

[[ 4.  5.  8. 13. 20.]
 [ 2.  1.  2.  5. 10.]
 [ 4.  1.  0.  1.  4.]
 [10.  5.  2.  1.  2.]
 [20. 13.  8.  5.  4.]] 



In [29]:
# RESHAPING AND CONCATENATION
# Partendo da un qualsiasi array posso cambiargli la forma 
a = np.arange(0, 6) #1 riga 6 valori nell'array
m = a.reshape(3, 2) #disporre questi valori in 3 righe 2 colonne
print("original:", a, '\n')
print("reshaped:", m, '\n')
back_to_a = m.flatten() #riporto ad a che era 1dimensionale
print("flattened array (back to original):", back_to_a, '\n')

# L'operazione di concatenare è un pò complessa se si hanno dimensioni diverse
a = np.array([1, 2])
b = np.array([3, 4, 5, 6])
c = np.array([7, 8, 9]) #tutti e 3 sono 1d
print("1D concatenation:", np.concatenate((a, b, c)),'\n') #Porta tutto ad una dimensione
a = np.array([[1, 2], [3, 4]]) #parto da 2d
b = np.array([[5, 6], [7, 8]]) #altro 2d
print("default 2D concatenation:",'\n', np.concatenate((a, b)),'\n') #ottengo 1 sotto l'altra 4 righe 2 col
print("concatenation along the first axis:",'\n', np.concatenate((a, b), axis=0), '\n') #sotto 4x2
print("concatenation along the second axis:",'\n', np.concatenate((a, b), axis=1), '\n') #affianco 2x4

original: [0 1 2 3 4 5] 

reshaped: [[0 1]
 [2 3]
 [4 5]] 

flattened array (back to original): [0 1 2 3 4 5] 

1D concatenation: [1 2 3 4 5 6 7 8 9] 

default 2D concatenation: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

concatenation along the first axis: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

concatenation along the second axis: 
 [[1 2 5 6]
 [3 4 7 8]] 



In [ ]:
# COPIE E VIEWS
a = np.array([1, 2, 3])
b = a # tutte le modifiche di a modificano anche b
c = a.copy() # faccio una copia, così se modifico quella originale resta uguale

In [2]:
# INDEXING
a = np.arange(10)
print(a[0], a[3], a[-1]) #il -1 printa l'ultimo valore perchè parte da destra e va a sinsitra
print(a[2:9:3]) #da 2 a 9 a passi di 3
print(a[::-1]) #reverse (se lascio i primi due vuoti prendo tutto)

0 3 9
[2 5 8]
[9 8 7 6 5 4 3 2 1 0]


In [17]:
#from IPython.display import Image
#Image("numpy_indexing.png")
a = np.array([[0,1,2,3,4,5],
             [10,11,12,13,14,15],
             [20,21,22,23,24,25],
             [30,31,32,33,34,35],
             [40,41,42,43,44,45],
             [50,51,52,53,54,55]])
print(a)
x = np.array([0,1,2,3,4,5])
b = np.array([10,20,30,40,50])
a = np.array([x + j for j in np.insert(b, 0, 0)])
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
